In [1]:
# Librerias
import numpy as np
import pandas as pd

## **Datos**

In [ ]:
aranzazu = pd.read_csv('../data/bronze_meteorologicos_aranzazu.csv', encoding='utf8')

In [115]:
aranzazu.head(5)

,Time,Interval,Indoor Temperature(°C),Indoor Humidity(%),Outdoor Temperature(°C),Outdoor Humidity(%),Relative Pressure(hpa),Absolute Pressure(hpa),Wind Speed(km/h),Gust(km/h),Wind Direction,DewPoint(°C),WindChill(°C),Hour Rainfall(mm),24 Hour Rainfall(mm),Week Rainfall(mm),Month Rainfall(mm),Total Rainfall(mm),Light(lux),UVI
0,2018/01/01 1:02:06 a.m.,60,"20,8",74,"16,1",93,1.013,"826,7","1,1","3,6",S,15,"16,1",0,0,"12,9",0,"437,1",0,0
1,2018/01/01 2:02:06 a.m.,60,"20,8",74,"16,2",93,"1.012,2","825,9",0,0,E,"15,1","16,2",0,0,"12,9",0,"437,1",0,0
2,2018/01/01 3:02:06 a.m.,60,"20,6",75,"15,9",95,1.012,"825,7",0,0,NW,"15,1","15,9",0,0,"12,9",0,"437,1",0,0
3,2018/01/01 4:02:06 a.m.,60,"20,5",74,16,95,"1.011,7","825,4",0,"1,1",SE,"15,2",16,0,0,"12,9",0,"437,1",0,0
4,2018/01/01 5:02:06 a.m.,60,"20,5",75,"15,6",95,1.012,"825,7","1,1","2,5",S,"14,8","15,6",0,0,"12,9",0,"437,1",0,0

In [116]:
aranzazu.info()

<class 'pandas.DataFrame'>
RangeIndex: 19190 entries, 0 to 19189
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Time                     19190 non-null  str
 1   Interval                 19190 non-null  int64
 2   Indoor Temperature(°C)   19190 non-null  str
 3   Indoor Humidity(%)       19190 non-null  int64
 4   Outdoor Temperature(°C)  19190 non-null  str
 5   Outdoor Humidity(%)      19190 non-null  int64
 6   Relative Pressure(hpa)   19190 non-null  str
 7   Absolute Pressure(hpa)   19190 non-null  str
 8   Wind Speed(km/h)         19190 non-null  str
 9   Gust(km/h)               19190 non-null  str
 10  Wind Direction           19190 non-null  str
 11  DewPoint(°C)             19190 non-null  str
 12  WindChill(°C)            19190 non-null  str
 13  Hour Rainfall(mm)        19190 non-null  str
 14  24 Hour Rainfall(mm)     19190 non-null  str
 15  Week Rainfall(mm)        19190 non-null  str
 16  Month Rainfall(mm)       19190 non-null  str
 17  Total Rainfall(mm)       19190 non-null  str
 18  Light(lux)               19190 non-null  str
 19  UVI                      19190 non-null  int64
dtypes: int64(4), str(16)
memory usage: 2.9 MB

> **Hallazgos:**  
> - Variables numéricas (mediciones meteorologicas) codificadas como `str`.
> - Variable de tiempo codificada como `str`.

## **Limpieza**

### **Convertir `Time` a variable de tiempo**

In [117]:
aranzazu["Time_dt"] = pd.to_datetime(
    aranzazu["Time"], format="mixed",
    dayfirst=False, errors="coerce")

In [118]:
type(aranzazu['Time_dt'][1])

pandas.Timestamp

In [119]:
aranzazu[["Time", "Time_dt"]].head(10)

                       Time             Time_dt
0   2018/01/01 1:02:06 a.m. 2018-01-01 01:02:06
1   2018/01/01 2:02:06 a.m. 2018-01-01 02:02:06
2   2018/01/01 3:02:06 a.m. 2018-01-01 03:02:06
3   2018/01/01 4:02:06 a.m. 2018-01-01 04:02:06
4   2018/01/01 5:02:06 a.m. 2018-01-01 05:02:06
5   2018/01/01 6:02:06 a.m. 2018-01-01 06:02:06
6   2018/01/01 7:02:06 a.m. 2018-01-01 07:02:06
7   2018/01/01 8:02:06 a.m. 2018-01-01 08:02:06
8   2018/01/01 9:02:06 a.m. 2018-01-01 09:02:06
9  2018/01/01 10:02:06 a.m. 2018-01-01 10:02:06

In [120]:
aranzazu = aranzazu.drop(columns=['Time'])
aranzazu.columns

Index(['Interval', 'Indoor Temperature(°C)', 'Indoor Humidity(%)',
       'Outdoor Temperature(°C)', 'Outdoor Humidity(%)',
       'Relative Pressure(hpa)', 'Absolute Pressure(hpa)', 'Wind Speed(km/h)',
       'Gust(km/h)', 'Wind Direction', 'DewPoint(°C)', 'WindChill(°C)',
       'Hour Rainfall(mm)', '24 Hour Rainfall(mm)', 'Week Rainfall(mm)',
       'Month Rainfall(mm)', 'Total Rainfall(mm)', 'Light(lux)', 'UVI',
       'Time_dt'],
      dtype='str')

### **Conversión de variables numéricas originalmente codificadas como `str`**

In [121]:
numeric_cols = [
    "Indoor Temperature(°C)",
    "Outdoor Temperature(°C)",
    "Relative Pressure(hpa)",
    "Absolute Pressure(hpa)",
    "Wind Speed(km/h)",
    "Gust(km/h)",
    "DewPoint(°C)",
    "WindChill(°C)",
    "Hour Rainfall(mm)",
    "24 Hour Rainfall(mm)",
    "Week Rainfall(mm)",
    "Month Rainfall(mm)",
    "Total Rainfall(mm)",
    "Light(lux)"]

for col in numeric_cols:
    aranzazu[col] = (
        aranzazu[col]
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False))
    aranzazu[col] = pd.to_numeric(aranzazu[col], errors="coerce")

for col in numeric_cols:
    aranzazu[col] = pd.to_numeric(aranzazu[col], errors="coerce")

missing = aranzazu.isna().sum().sort_values(ascending=False)
missing

Interval                   0
Indoor Temperature(°C)     0
Indoor Humidity(%)         0
Outdoor Temperature(°C)    0
Outdoor Humidity(%)        0
Relative Pressure(hpa)     0
Absolute Pressure(hpa)     0
Wind Speed(km/h)           0
Gust(km/h)                 0
Wind Direction             0
DewPoint(°C)               0
WindChill(°C)              0
Hour Rainfall(mm)          0
24 Hour Rainfall(mm)       0
Week Rainfall(mm)          0
Month Rainfall(mm)         0
Total Rainfall(mm)         0
Light(lux)                 0
UVI                        0
Time_dt                    0
dtype: int64

In [122]:
aranzazu.head(5)

,Interval,Indoor Temperature(°C),Indoor Humidity(%),Outdoor Temperature(°C),Outdoor Humidity(%),Relative Pressure(hpa),Absolute Pressure(hpa),Wind Speed(km/h),Gust(km/h),Wind Direction,DewPoint(°C),WindChill(°C),Hour Rainfall(mm),24 Hour Rainfall(mm),Week Rainfall(mm),Month Rainfall(mm),Total Rainfall(mm),Light(lux),UVI,Time_dt
0,60,20.8,74,16.1,93,1013.0,826.7,1.1,3.6,S,15.0,16.1,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 01:02:06
1,60,20.8,74,16.2,93,1012.2,825.9,0.0,0.0,E,15.1,16.2,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 02:02:06
2,60,20.6,75,15.9,95,1012.0,825.7,0.0,0.0,NW,15.1,15.9,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 03:02:06
3,60,20.5,74,16.0,95,1011.7,825.4,0.0,1.1,SE,15.2,16.0,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 04:02:06
4,60,20.5,75,15.6,95,1012.0,825.7,1.1,2.5,S,14.8,15.6,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 05:02:06

In [123]:
aranzazu.info()

<class 'pandas.DataFrame'>
RangeIndex: 19190 entries, 0 to 19189
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Interval                 19190 non-null  int64
 1   Indoor Temperature(°C)   19190 non-null  float64
 2   Indoor Humidity(%)       19190 non-null  int64
 3   Outdoor Temperature(°C)  19190 non-null  float64
 4   Outdoor Humidity(%)      19190 non-null  int64
 5   Relative Pressure(hpa)   19190 non-null  float64
 6   Absolute Pressure(hpa)   19190 non-null  float64
 7   Wind Speed(km/h)         19190 non-null  float64
 8   Gust(km/h)               19190 non-null  float64
 9   Wind Direction           19190 non-null  str
 10  DewPoint(°C)             19190 non-null  float64
 11  WindChill(°C)            19190 non-null  float64
 12  Hour Rainfall(mm)        19190 non-null  float64
 13  24 Hour Rainfall(mm)     19190 non-null  float64
 14  Week Rainfall(mm)        19190 non-null  float64
 15  Month Rainfall(mm)       19190 non-null  float64
 16  Total Rainfall(mm)       19190 non-null  float64
 17  Light(lux)               19190 non-null  float64
 18  UVI                      19190 non-null  int64
 19  Time_dt                  19190 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(14), int64(4), str(1)
memory usage: 2.9 MB

### **Conversión de Nulos de `Wind Direction` codificados como `---`, a `NaN`**

In [124]:
aranzazu['Wind Direction'].unique()

<StringArray>
[  'S',   'E',  'NW',  'SE',  'NE', 'ENE',   'N',  'SW',   'W', 'NNW', 'SSW',
 'WNW', 'WSW', 'NNE', 'SSE', '---']
Length: 16, dtype: str

In [125]:
# Registros nulos de `Wind Direction`
aranzazu[aranzazu['Wind Direction'] == '---']

,Interval,Indoor Temperature(°C),Indoor Humidity(%),Outdoor Temperature(°C),Outdoor Humidity(%),Relative Pressure(hpa),Absolute Pressure(hpa),Wind Speed(km/h),Gust(km/h),Wind Direction,DewPoint(°C),WindChill(°C),Hour Rainfall(mm),24 Hour Rainfall(mm),Week Rainfall(mm),Month Rainfall(mm),Total Rainfall(mm),Light(lux),UVI,Time_dt
6260,30,22.4,68,22.4,62,1011.5,826.2,11.2,15.8,---,14.8,20.9,0.0,0.0,6.0,98.4,149.4,45814.0,0,2018-08-31 09:06:48
8211,30,25.1,47,22.6,52,1010.6,825.3,3.6,7.2,---,12.3,22.6,0.0,19.2,51.0,96.3,364.8,19696.1,0,2018-10-11 17:21:42
12403,30,26.0,58,27.4,49,1012.3,827.0,7.2,9.7,---,15.8,27.1,0.0,0.0,32.7,38.1,1629.9,80932.4,0,2019-02-15 11:53:46

In [126]:
# Conversión
aranzazu = aranzazu.replace("---", np.nan)
aranzazu.info()

<class 'pandas.DataFrame'>
RangeIndex: 19190 entries, 0 to 19189
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Interval                 19190 non-null  int64
 1   Indoor Temperature(°C)   19190 non-null  float64
 2   Indoor Humidity(%)       19190 non-null  int64
 3   Outdoor Temperature(°C)  19190 non-null  float64
 4   Outdoor Humidity(%)      19190 non-null  int64
 5   Relative Pressure(hpa)   19190 non-null  float64
 6   Absolute Pressure(hpa)   19190 non-null  float64
 7   Wind Speed(km/h)         19190 non-null  float64
 8   Gust(km/h)               19190 non-null  float64
 9   Wind Direction           19187 non-null  str
 10  DewPoint(°C)             19190 non-null  float64
 11  WindChill(°C)            19190 non-null  float64
 12  Hour Rainfall(mm)        19190 non-null  float64
 13  24 Hour Rainfall(mm)     19190 non-null  float64
 14  Week Rainfall(mm)        19190 non-null  float64
 15  Month Rainfall(mm)       19190 non-null  float64
 16  Total Rainfall(mm)       19190 non-null  float64
 17  Light(lux)               19190 non-null  float64
 18  UVI                      19190 non-null  int64
 19  Time_dt                  19190 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(14), int64(4), str(1)
memory usage: 2.9 MB

In [127]:
print(aranzazu['Wind Direction'].unique())

aranzazu[aranzazu['Wind Direction'] == '---']

<StringArray>
[  'S',   'E',  'NW',  'SE',  'NE', 'ENE',   'N',  'SW',   'W', 'NNW', 'SSW',
 'WNW', 'WSW', 'NNE', 'SSE',   nan]
Length: 16, dtype: str

Empty DataFrame
Columns: [Interval, Indoor Temperature(°C), Indoor Humidity(%), Outdoor Temperature(°C), Outdoor Humidity(%), Relative Pressure(hpa), Absolute Pressure(hpa), Wind Speed(km/h), Gust(km/h), Wind Direction, DewPoint(°C), WindChill(°C), Hour Rainfall(mm), 24 Hour Rainfall(mm), Week Rainfall(mm), Month Rainfall(mm), Total Rainfall(mm), Light(lux), UVI, Time_dt]
Index: []

### **Eliminación de la variable `UVI`**

In [128]:
aranzazu['UVI'].unique()

array([0])

In [ ]:
# Eliminación de la columna `UVI`
aranzazu = aranzazu.drop(columns=['UVI'])
aranzazu.columns

Index(['Interval', 'Indoor Temperature(°C)', 'Indoor Humidity(%)',
       'Outdoor Temperature(°C)', 'Outdoor Humidity(%)',
       'Relative Pressure(hpa)', 'Absolute Pressure(hpa)', 'Wind Speed(km/h)',
       'Gust(km/h)', 'Wind Direction', 'DewPoint(°C)', 'WindChill(°C)',
       'Hour Rainfall(mm)', '24 Hour Rainfall(mm)', 'Week Rainfall(mm)',
       'Month Rainfall(mm)', 'Total Rainfall(mm)', 'Light(lux)', 'Time_dt'],
      dtype='str')

## **EDA**

### **Faltantes**

Únicamente se reportan faltantes en la variable `Wind Direction`.

In [ ]:
# Tabla de valores faltantes del dataset Aranzazu

faltantes = aranzazu['Wind Direction'].isna().sum()

porcentaje_faltantes = (faltantes / len(aranzazu)) * 100

tabla_faltantes = pd.DataFrame({
    "Variable": ["Wind Direction"],
    "Valores faltantes": [faltantes],
    "Porcentaje (%)": [porcentaje_faltantes.round(2)]
})

tabla_faltantes

         Variable  Valores faltantes  Porcentaje (%)
0  Wind Direction                  3            0.02

### **Distribuciones**

### **Correlaciones**