In [140]:
import pandas as pd

In [141]:
m = pd.read_csv('../data/meteorologicos.csv',encoding='utf8')

In [142]:
m.info()

<class 'pandas.DataFrame'>
RangeIndex: 19190 entries, 0 to 19189
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Time                     19190 non-null  str
 1   Interval                 19190 non-null  int64
 2   Indoor Temperature(°C)   19190 non-null  str
 3   Indoor Humidity(%)       19190 non-null  int64
 4   Outdoor Temperature(°C)  19190 non-null  str
 5   Outdoor Humidity(%)      19190 non-null  int64
 6   Relative Pressure(hpa)   19190 non-null  str
 7   Absolute Pressure(hpa)   19190 non-null  str
 8   Wind Speed(km/h)         19190 non-null  str
 9   Gust(km/h)               19190 non-null  str
 10  Wind Direction           19190 non-null  str
 11  DewPoint(°C)             19190 non-null  str
 12  WindChill(°C)            19190 non-null  str
 13  Hour Rainfall(mm)        19190 non-null  str
 14  24 Hour Rainfall(mm)     19190 non-null  str
 15  Week Rainfall(mm)        19190 non-null  str
 16  Month Rainfall(mm)       19190 non-null  str
 17  Total Rainfall(mm)       19190 non-null  str
 18  Light(lux)               19190 non-null  str
 19  UVI                      19190 non-null  int64
dtypes: int64(4), str(16)
memory usage: 2.9 MB

In [143]:
m.head()

,Time,Interval,Indoor Temperature(°C),Indoor Humidity(%),Outdoor Temperature(°C),Outdoor Humidity(%),Relative Pressure(hpa),Absolute Pressure(hpa),Wind Speed(km/h),Gust(km/h),Wind Direction,DewPoint(°C),WindChill(°C),Hour Rainfall(mm),24 Hour Rainfall(mm),Week Rainfall(mm),Month Rainfall(mm),Total Rainfall(mm),Light(lux),UVI
0,2018/01/01 1:02:06 a.m.,60,"20,8",74,"16,1",93,1.013,"826,7","1,1","3,6",S,15,"16,1",0,0,"12,9",0,"437,1",0,0
1,2018/01/01 2:02:06 a.m.,60,"20,8",74,"16,2",93,"1.012,2","825,9",0,0,E,"15,1","16,2",0,0,"12,9",0,"437,1",0,0
2,2018/01/01 3:02:06 a.m.,60,"20,6",75,"15,9",95,1.012,"825,7",0,0,NW,"15,1","15,9",0,0,"12,9",0,"437,1",0,0
3,2018/01/01 4:02:06 a.m.,60,"20,5",74,16,95,"1.011,7","825,4",0,"1,1",SE,"15,2",16,0,0,"12,9",0,"437,1",0,0
4,2018/01/01 5:02:06 a.m.,60,"20,5",75,"15,6",95,1.012,"825,7","1,1","2,5",S,"14,8","15,6",0,0,"12,9",0,"437,1",0,0

In [144]:
m.columns[1:]

Index(['Interval', 'Indoor Temperature(°C)', 'Indoor Humidity(%)',
       'Outdoor Temperature(°C)', 'Outdoor Humidity(%)',
       'Relative Pressure(hpa)', 'Absolute Pressure(hpa)', 'Wind Speed(km/h)',
       'Gust(km/h)', 'Wind Direction', 'DewPoint(°C)', 'WindChill(°C)',
       'Hour Rainfall(mm)', '24 Hour Rainfall(mm)', 'Week Rainfall(mm)',
       'Month Rainfall(mm)', 'Total Rainfall(mm)', 'Light(lux)', 'UVI'],
      dtype='str')

In [145]:
m.info()

<class 'pandas.DataFrame'>
RangeIndex: 19190 entries, 0 to 19189
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Time                     19190 non-null  str
 1   Interval                 19190 non-null  int64
 2   Indoor Temperature(°C)   19190 non-null  str
 3   Indoor Humidity(%)       19190 non-null  int64
 4   Outdoor Temperature(°C)  19190 non-null  str
 5   Outdoor Humidity(%)      19190 non-null  int64
 6   Relative Pressure(hpa)   19190 non-null  str
 7   Absolute Pressure(hpa)   19190 non-null  str
 8   Wind Speed(km/h)         19190 non-null  str
 9   Gust(km/h)               19190 non-null  str
 10  Wind Direction           19190 non-null  str
 11  DewPoint(°C)             19190 non-null  str
 12  WindChill(°C)            19190 non-null  str
 13  Hour Rainfall(mm)        19190 non-null  str
 14  24 Hour Rainfall(mm)     19190 non-null  str
 15  Week Rainfall(mm)        19190 non-null  str
 16  Month Rainfall(mm)       19190 non-null  str
 17  Total Rainfall(mm)       19190 non-null  str
 18  Light(lux)               19190 non-null  str
 19  UVI                      19190 non-null  int64
dtypes: int64(4), str(16)
memory usage: 2.9 MB

In [146]:
m['Time']

0        2018/01/01 1:02:06 a.m.
1        2018/01/01 2:02:06 a.m.
2        2018/01/01 3:02:06 a.m.
3        2018/01/01 4:02:06 a.m.
4        2018/01/01 5:02:06 a.m.
                  ...
19185    2019-09-11T15:57:08.000
19186    2019-09-11T16:27:08.000
19187    2019-09-11T16:57:08.000
19188    2019-09-11T17:27:08.000
19189    2019-09-11T17:57:08.000
Name: Time, Length: 19190, dtype: str

In [147]:
m["Time_dt"] = pd.to_datetime(
    m["Time"],
    format="mixed",
    dayfirst=False,
    errors="coerce"
)

In [148]:
m[["Time", "Time_dt"]].head(10)

                       Time             Time_dt
0   2018/01/01 1:02:06 a.m. 2018-01-01 01:02:06
1   2018/01/01 2:02:06 a.m. 2018-01-01 02:02:06
2   2018/01/01 3:02:06 a.m. 2018-01-01 03:02:06
3   2018/01/01 4:02:06 a.m. 2018-01-01 04:02:06
4   2018/01/01 5:02:06 a.m. 2018-01-01 05:02:06
5   2018/01/01 6:02:06 a.m. 2018-01-01 06:02:06
6   2018/01/01 7:02:06 a.m. 2018-01-01 07:02:06
7   2018/01/01 8:02:06 a.m. 2018-01-01 08:02:06
8   2018/01/01 9:02:06 a.m. 2018-01-01 09:02:06
9  2018/01/01 10:02:06 a.m. 2018-01-01 10:02:06

In [149]:
m[["Time", "Time_dt"]].tail(10)

                          Time             Time_dt
19180  2019-09-11T13:27:08.000 2019-09-11 13:27:08
19181  2019-09-11T13:57:08.000 2019-09-11 13:57:08
19182  2019-09-11T14:27:08.000 2019-09-11 14:27:08
19183  2019-09-11T14:57:08.000 2019-09-11 14:57:08
19184  2019-09-11T15:27:08.000 2019-09-11 15:27:08
19185  2019-09-11T15:57:08.000 2019-09-11 15:57:08
19186  2019-09-11T16:27:08.000 2019-09-11 16:27:08
19187  2019-09-11T16:57:08.000 2019-09-11 16:57:08
19188  2019-09-11T17:27:08.000 2019-09-11 17:27:08
19189  2019-09-11T17:57:08.000 2019-09-11 17:57:08

In [150]:
m["Time_dt"] = pd.to_datetime(
    m["Time"],
    format="mixed",
    errors="coerce"
)

m["delta"] = m["Time_dt"].diff()

m["delta"].value_counts().head(20)

delta
0 days 00:30:00     16929
0 days 01:00:00      1853
0 days 00:16:14        87
0 days 00:43:46        86
0 days 00:55:46        63
0 days 00:04:14        62
0 days 00:31:00        15
30 days 00:30:00        6
0 days 13:30:00         5
0 days 01:30:00         5
0 days 00:35:00         4
29 days 00:30:00        4
0 days 00:41:00         3
0 days 00:46:00         3
0 days 00:32:00         3
0 days 00:47:00         2
0 days 00:36:00         2
0 days 00:39:00         2
0 days 01:18:00         2
0 days 01:38:00         2
Name: count, dtype: int64

In [151]:
m["Time_dt"] = pd.to_datetime(
    m["Time"],
    format="mixed",
    errors="coerce"
)

m = m.sort_values("Time_dt")

m["delta"] = m["Time_dt"].diff()

In [152]:
m.set_index("Time_dt").resample("ME").size()

Time_dt
2018-01-31     232
2018-02-28     822
2018-03-31     714
2018-04-30    1019
2018-05-31     543
2018-06-30     696
2018-07-31     783
2018-08-31    1481
2018-09-30    1413
2018-10-31    1072
2018-11-30    1413
2018-12-31    1457
2019-01-31     113
2019-02-28    1387
2019-03-31    1463
2019-04-30     224
2019-05-31     958
2019-06-30     971
2019-07-31     782
2019-08-31     970
2019-09-30     533
2019-10-31      48
2019-11-30      48
2019-12-31      48
Freq: ME, dtype: int64

In [153]:
print(m.groupby(m["Time_dt"].dt.to_period("M"))["Time_dt"].agg(
    ["min", "max", "count"]
))

                        min                 max  count
Time_dt
2018-01 2018-01-01 01:02:06 2018-01-10 15:41:49    232
2018-02 2018-02-01 01:02:53 2018-02-28 23:14:53    822
2018-03 2018-03-01 01:03:48 2018-03-31 23:57:32    714
2018-04 2018-04-01 01:57:32 2018-04-30 11:34:32   1019
2018-05 2018-05-01 01:04:32 2018-05-12 08:04:32    543
2018-06 2018-06-15 22:47:12 2018-06-30 11:42:12    696
2018-07 2018-07-01 01:12:12 2018-07-17 08:12:12    783
2018-08 2018-08-01 01:20:48 2018-08-31 23:36:48   1481
2018-09 2018-09-01 01:06:48 2018-09-30 11:46:42   1413
2018-10 2018-10-01 01:16:42 2018-10-23 10:51:42   1072
2018-11 2018-11-01 01:00:22 2018-11-30 11:49:22   1413
2018-12 2018-12-01 01:19:22 2018-12-31 11:54:53   1457
2019-01 2019-01-01 01:24:53 2019-01-05 23:46:58    113
2019-02 2019-02-01 01:26:46 2019-02-28 23:53:46   1387
2019-03 2019-03-02 10:51:44 2019-03-31 23:30:44   1463
2019-04 2019-04-01 01:00:44 2019-04-05 23:46:58    224
2019-05 2019-05-05 00:16:58 2019-05-31 23:45:58    958
2019-06 2019-06-01 01:15:58 2019-06-20 08:15:58    971
2019-07 2019-07-01 01:10:51 2019-07-16 08:29:51    782
2019-08 2019-08-03 12:22:34 2019-08-22 17:22:34    970
2019-09 2019-09-01 13:27:08 2019-09-11 17:57:08    533
2019-10 2019-10-05 00:16:58 2019-10-05 23:46:58     48
2019-11 2019-11-05 00:16:58 2019-11-05 23:46:58     48
2019-12 2019-12-05 00:16:58 2019-12-05 23:46:58     48

In [154]:
print(m[m["Time_dt"].dt.year == 2019].groupby(
    m["Time_dt"].dt.month
)["Time_dt"].agg(["min", "max", "count"]))

                        min                 max  count
Time_dt
1       2019-01-01 01:24:53 2019-01-05 23:46:58    113
2       2019-02-01 01:26:46 2019-02-28 23:53:46   1387
3       2019-03-02 10:51:44 2019-03-31 23:30:44   1463
4       2019-04-01 01:00:44 2019-04-05 23:46:58    224
5       2019-05-05 00:16:58 2019-05-31 23:45:58    958
6       2019-06-01 01:15:58 2019-06-20 08:15:58    971
7       2019-07-01 01:10:51 2019-07-16 08:29:51    782
8       2019-08-03 12:22:34 2019-08-22 17:22:34    970
9       2019-09-01 13:27:08 2019-09-11 17:57:08    533
10      2019-10-05 00:16:58 2019-10-05 23:46:58     48
11      2019-11-05 00:16:58 2019-11-05 23:46:58     48
12      2019-12-05 00:16:58 2019-12-05 23:46:58     48

In [155]:
ago = m[
    (m["Time_dt"] >= "2018-08-01") &
    (m["Time_dt"] < "2018-09-01")
].copy()

ago["delta"] = ago["Time_dt"].diff()

ago["delta"].value_counts().head(10)

delta
0 days 00:30:00    1475
0 days 00:46:00       2
0 days 01:00:00       1
0 days 01:43:00       1
0 days 00:31:00       1
Name: count, dtype: int64

In [156]:
feb = m[
    (m["Time_dt"] >= "2019-02-01") &
    (m["Time_dt"] < "2019-03-01")
].copy()

feb["delta"] = feb["Time_dt"].diff()

feb["delta"].value_counts().head(10)

delta
0 days 00:30:00    1287
0 days 00:23:12      48
0 days 00:06:48      48
0 days 01:25:00       1
0 days 00:50:00       1
0 days 00:42:00       1
Name: count, dtype: int64

In [157]:
periodo = m[
    (m["Time_dt"] >= "2018-08-01") &
    (m["Time_dt"] < "2019-01-01")
].copy()

periodo.shape

(6836, 22)

In [158]:
periodo["delta"] = periodo["Time_dt"].diff()

periodo["delta"].value_counts().head(10)

delta
0 days 00:30:00    6803
0 days 00:31:00       6
0 days 00:46:00       2
0 days 13:30:00       2
0 days 00:39:00       2
0 days 01:18:00       2
0 days 01:38:00       2
0 days 01:03:00       2
0 days 01:00:00       1
0 days 01:43:00       1
Name: count, dtype: int64

In [159]:
print(periodo[periodo["delta"] != pd.Timedelta("30min")][
    ["Time_dt", "delta"]
])

                  Time_dt           delta
4809  2018-08-01 01:20:48             NaT
5008  2018-08-05 05:20:48 0 days 01:00:00
5775  2018-08-21 06:03:48 0 days 01:43:00
5776  2018-08-21 06:49:48 0 days 00:46:00
5777  2018-08-21 07:35:48 0 days 00:46:00
5782  2018-08-21 10:06:48 0 days 00:31:00
6290  2018-09-01 01:06:48 0 days 01:30:00
6315  2018-09-01 13:37:48 0 days 00:31:00
6558  2018-09-06 15:46:42 0 days 01:08:54
7703  2018-10-01 01:16:42 0 days 13:30:00
7768  2018-10-02 09:55:42 0 days 00:39:00
7769  2018-10-02 11:13:42 0 days 01:18:00
7770  2018-10-02 12:51:42 0 days 01:38:00
8775  2018-11-01 01:00:22 8 days 14:08:40
8954  2018-11-04 18:31:22 0 days 00:31:00
8955  2018-11-04 19:34:22 0 days 01:03:00
8956  2018-11-04 20:09:22 0 days 00:35:00
8957  2018-11-04 20:40:22 0 days 00:31:00
8958  2018-11-04 21:21:22 0 days 00:41:00
8963  2018-11-04 23:52:22 0 days 00:31:00
10153 2018-11-29 18:49:22 0 days 00:27:00
10188 2018-12-01 01:19:22 0 days 13:30:00
10278 2018-12-02 22:28:22 0 days 00:39:00
10279 2018-12-02 23:46:22 0 days 01:18:00
10280 2018-12-03 01:24:22 0 days 01:38:00
10439 2018-12-06 08:27:39 0 days 00:03:17
10440 2018-12-06 09:01:53 0 days 00:34:14
10803 2018-12-13 22:32:53 0 days 00:31:00
11195 2018-12-22 02:34:53 0 days 00:32:00
11196 2018-12-22 03:07:53 0 days 00:33:00
11197 2018-12-22 03:45:53 0 days 00:38:00
11198 2018-12-22 04:21:53 0 days 00:36:00
11199 2018-12-22 05:24:53 0 days 01:03:00

In [160]:
m.head(20)

,Time,Interval,Indoor Temperature(°C),Indoor Humidity(%),Outdoor Temperature(°C),Outdoor Humidity(%),Relative Pressure(hpa),Absolute Pressure(hpa),Wind Speed(km/h),Gust(km/h),...,WindChill(°C),Hour Rainfall(mm),24 Hour Rainfall(mm),Week Rainfall(mm),Month Rainfall(mm),Total Rainfall(mm),Light(lux),UVI,Time_dt,delta
0,2018/01/01 1:02:06 a.m.,60,"20,8",74,"16,1",93,1.013,"826,7","1,1","3,6",...,"16,1",0,0,"12,9",0,"437,1",0,0,2018-01-01 01:02:06,NaT
1,2018/01/01 2:02:06 a.m.,60,"20,8",74,"16,2",93,"1.012,2","825,9",0,0,...,"16,2",0,0,"12,9",0,"437,1",0,0,2018-01-01 02:02:06,0 days 01:00:00
2,2018/01/01 3:02:06 a.m.,60,"20,6",75,"15,9",95,1.012,"825,7",0,0,...,"15,9",0,0,"12,9",0,"437,1",0,0,2018-01-01 03:02:06,0 days 01:00:00
3,2018/01/01 4:02:06 a.m.,60,"20,5",74,16,95,"1.011,7","825,4",0,"1,1",...,16,0,0,"12,9",0,"437,1",0,0,2018-01-01 04:02:06,0 days 01:00:00
4,2018/01/01 5:02:06 a.m.,60,"20,5",75,"15,6",95,1.012,"825,7","1,1","2,5",...,"15,6",0,0,"12,9",0,"437,1",0,0,2018-01-01 05:02:06,0 days 01:00:00
5,2018/01/01 6:02:06 a.m.,60,"20,3",74,"15,4",96,"1.012,2","825,9","1,1","2,5",...,"15,4",0,0,"12,9",0,"437,1",0,0,2018-01-01 06:02:06,0 days 01:00:00
6,2018/01/01 7:02:06 a.m.,60,"20,2",73,"15,1",96,"1.012,8","826,5","1,1","2,5",...,"15,1",0,0,"12,9",0,"437,1",1.701,0,2018-01-01 07:02:06,0 days 01:00:00
7,2018/01/01 8:02:06 a.m.,60,"20,4",73,"21,2",71,"1.013,5","827,2","2,5","3,6",...,"21,2",0,0,"12,9",0,"437,1","11.884,7",0,2018-01-01 08:02:06,0 days 01:00:00
8,2018/01/01 9:02:06 a.m.,60,21,71,"19,3",79,1.014,"827,7","3,6",5,...,"19,3",0,0,"12,9",0,"437,1","14.300,5",0,2018-01-01 09:02:06,0 days 01:00:00
9,2018/01/01 10:02:06 a.m.,60,"21,4",71,"21,6",73,"1.014,4","828,1","7,2","9,7",...,21,0,0,"12,9",0,"437,1","27.187,9",0,2018-01-01 10:02:06,0 days 01:00:00
10,2018/01/01 11:02:06 a.m.,60,22,70,"20,3",75,1.014,"827,7",5,"9,7",...,"20,3","0,3","0,3","13,2","0,3","437,4","16.415,5",0,2018-01-01 11:02:06,0 days 01:00:00
11,2018/01/01 12:02:06 p.m.,60,22,70,"20,3",78,"1.013,5","827,2","6,1","8,6",...,"20,3",0,"0,3","13,2","0,3","437,4","13.139,6",0,2018-01-01 12:02:06,0 days 01:00:00
12,2018/01/01 1:02:06 p.m.,60,"22,1",70,21,72,"1.012,6","826,3","3,6","6,1",...,21,0,"0,3","13,2","0,3","437,4","21.980,3",0,2018-01-01 13:02:06,0 days 01:00:00
13,2018/01/01 2:02:06 p.m.,60,"22,3",70,"20,4",79,1.012,"825,7","2,5","3,6",...,"20,4",0,"0,3","13,2","0,3","437,4","12.274,8",0,2018-01-01 14:02:06,0 days 01:00:00
14,2018/01/01 3:02:06 p.m.,60,"22,3",70,"21,6",73,"1.010,8","824,5","3,6","7,2",...,"21,6",0,"0,3","13,2","0,3","437,4","12.110,3",0,2018-01-01 15:02:06,0 days 01:00:00
15,2018/01/01 4:02:06 p.m.,60,"22,6",69,"21,6",66,"1.010,7","824,4","8,6","9,7",...,"20,6",0,"0,3","13,2","0,3","437,4","14.742,3",0,2018-01-01 16:02:06,0 days 01:00:00
16,2018/01/01 5:02:06 p.m.,60,"22,4",69,"18,3",87,1.011,"824,7","3,6","6,1",...,"18,3",0,"0,3","13,2","0,3","437,4",8.738,0,2018-01-01 17:02:06,0 days 01:00:00
17,2018/01/01 6:02:06 p.m.,60,22,71,"17,3",89,1.011,"824,7","9,7","14,8",...,"15,5",0,"0,3","13,2","0,3","437,4",1.026,0,2018-01-01 18:02:06,0 days 01:00:00
18,2018/01/01 7:02:06 p.m.,60,"21,6",72,"16,7",92,"1.012,4","826,1","1,1","3,6",...,"16,7","2,4","2,7","15,6","2,7","439,8",0,0,2018-01-01 19:02:06,0 days 01:00:00
19,2018/01/01 8:02:06 p.m.,60,"21,3",74,16,96,"1.012,9","826,6",0,"1,1",...,16,"7,5","10,2","23,1","10,2","447,3",0,0,2018-01-01 20:02:06,0 days 01:00:00

In [161]:
numeric_cols = [
    "Indoor Temperature(°C)",
    "Outdoor Temperature(°C)",
    "Relative Pressure(hpa)",
    "Absolute Pressure(hpa)",
    "Wind Speed(km/h)",
    "Gust(km/h)",
    "DewPoint(°C)",
    "WindChill(°C)",
    "Hour Rainfall(mm)",
    "24 Hour Rainfall(mm)",
    "Week Rainfall(mm)",
    "Month Rainfall(mm)",
    "Total Rainfall(mm)",
    "Light(lux)"
]

for col in numeric_cols:
    m[col] = (
        m[col]
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
    )
    m[col] = pd.to_numeric(m[col], errors="coerce")

for col in numeric_cols:
    m[col] = pd.to_numeric(m[col], errors="coerce")

missing = m.isna().sum().sort_values(ascending=False)

missing

delta                      1
Time                       0
Indoor Temperature(°C)     0
Indoor Humidity(%)         0
Outdoor Temperature(°C)    0
Interval                   0
Outdoor Humidity(%)        0
Relative Pressure(hpa)     0
Wind Speed(km/h)           0
Absolute Pressure(hpa)     0
Wind Direction             0
DewPoint(°C)               0
WindChill(°C)              0
Gust(km/h)                 0
Hour Rainfall(mm)          0
24 Hour Rainfall(mm)       0
Month Rainfall(mm)         0
Week Rainfall(mm)          0
Total Rainfall(mm)         0
Light(lux)                 0
UVI                        0
Time_dt                    0
dtype: int64

In [162]:
m.head(20)

,Time,Interval,Indoor Temperature(°C),Indoor Humidity(%),Outdoor Temperature(°C),Outdoor Humidity(%),Relative Pressure(hpa),Absolute Pressure(hpa),Wind Speed(km/h),Gust(km/h),...,WindChill(°C),Hour Rainfall(mm),24 Hour Rainfall(mm),Week Rainfall(mm),Month Rainfall(mm),Total Rainfall(mm),Light(lux),UVI,Time_dt,delta
0,2018/01/01 1:02:06 a.m.,60,20.8,74,16.1,93,1013.0,826.7,1.1,3.6,...,16.1,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 01:02:06,NaT
1,2018/01/01 2:02:06 a.m.,60,20.8,74,16.2,93,1012.2,825.9,0.0,0.0,...,16.2,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 02:02:06,0 days 01:00:00
2,2018/01/01 3:02:06 a.m.,60,20.6,75,15.9,95,1012.0,825.7,0.0,0.0,...,15.9,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 03:02:06,0 days 01:00:00
3,2018/01/01 4:02:06 a.m.,60,20.5,74,16.0,95,1011.7,825.4,0.0,1.1,...,16.0,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 04:02:06,0 days 01:00:00
4,2018/01/01 5:02:06 a.m.,60,20.5,75,15.6,95,1012.0,825.7,1.1,2.5,...,15.6,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 05:02:06,0 days 01:00:00
5,2018/01/01 6:02:06 a.m.,60,20.3,74,15.4,96,1012.2,825.9,1.1,2.5,...,15.4,0.0,0.0,12.9,0.0,437.1,0.0,0,2018-01-01 06:02:06,0 days 01:00:00
6,2018/01/01 7:02:06 a.m.,60,20.2,73,15.1,96,1012.8,826.5,1.1,2.5,...,15.1,0.0,0.0,12.9,0.0,437.1,1701.0,0,2018-01-01 07:02:06,0 days 01:00:00
7,2018/01/01 8:02:06 a.m.,60,20.4,73,21.2,71,1013.5,827.2,2.5,3.6,...,21.2,0.0,0.0,12.9,0.0,437.1,11884.7,0,2018-01-01 08:02:06,0 days 01:00:00
8,2018/01/01 9:02:06 a.m.,60,21.0,71,19.3,79,1014.0,827.7,3.6,5.0,...,19.3,0.0,0.0,12.9,0.0,437.1,14300.5,0,2018-01-01 09:02:06,0 days 01:00:00
9,2018/01/01 10:02:06 a.m.,60,21.4,71,21.6,73,1014.4,828.1,7.2,9.7,...,21.0,0.0,0.0,12.9,0.0,437.1,27187.9,0,2018-01-01 10:02:06,0 days 01:00:00
10,2018/01/01 11:02:06 a.m.,60,22.0,70,20.3,75,1014.0,827.7,5.0,9.7,...,20.3,0.3,0.3,13.2,0.3,437.4,16415.5,0,2018-01-01 11:02:06,0 days 01:00:00
11,2018/01/01 12:02:06 p.m.,60,22.0,70,20.3,78,1013.5,827.2,6.1,8.6,...,20.3,0.0,0.3,13.2,0.3,437.4,13139.6,0,2018-01-01 12:02:06,0 days 01:00:00
12,2018/01/01 1:02:06 p.m.,60,22.1,70,21.0,72,1012.6,826.3,3.6,6.1,...,21.0,0.0,0.3,13.2,0.3,437.4,21980.3,0,2018-01-01 13:02:06,0 days 01:00:00
13,2018/01/01 2:02:06 p.m.,60,22.3,70,20.4,79,1012.0,825.7,2.5,3.6,...,20.4,0.0,0.3,13.2,0.3,437.4,12274.8,0,2018-01-01 14:02:06,0 days 01:00:00
14,2018/01/01 3:02:06 p.m.,60,22.3,70,21.6,73,1010.8,824.5,3.6,7.2,...,21.6,0.0,0.3,13.2,0.3,437.4,12110.3,0,2018-01-01 15:02:06,0 days 01:00:00
15,2018/01/01 4:02:06 p.m.,60,22.6,69,21.6,66,1010.7,824.4,8.6,9.7,...,20.6,0.0,0.3,13.2,0.3,437.4,14742.3,0,2018-01-01 16:02:06,0 days 01:00:00
16,2018/01/01 5:02:06 p.m.,60,22.4,69,18.3,87,1011.0,824.7,3.6,6.1,...,18.3,0.0,0.3,13.2,0.3,437.4,8738.0,0,2018-01-01 17:02:06,0 days 01:00:00
17,2018/01/01 6:02:06 p.m.,60,22.0,71,17.3,89,1011.0,824.7,9.7,14.8,...,15.5,0.0,0.3,13.2,0.3,437.4,1026.0,0,2018-01-01 18:02:06,0 days 01:00:00
18,2018/01/01 7:02:06 p.m.,60,21.6,72,16.7,92,1012.4,826.1,1.1,3.6,...,16.7,2.4,2.7,15.6,2.7,439.8,0.0,0,2018-01-01 19:02:06,0 days 01:00:00
19,2018/01/01 8:02:06 p.m.,60,21.3,74,16.0,96,1012.9,826.6,0.0,1.1,...,16.0,7.5,10.2,23.1,10.2,447.3,0.0,0,2018-01-01 20:02:06,0 days 01:00:00

In [163]:
m.info()

<class 'pandas.DataFrame'>
Index: 19190 entries, 0 to 15215
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Time                     19190 non-null  str
 1   Interval                 19190 non-null  int64
 2   Indoor Temperature(°C)   19190 non-null  float64
 3   Indoor Humidity(%)       19190 non-null  int64
 4   Outdoor Temperature(°C)  19190 non-null  float64
 5   Outdoor Humidity(%)      19190 non-null  int64
 6   Relative Pressure(hpa)   19190 non-null  float64
 7   Absolute Pressure(hpa)   19190 non-null  float64
 8   Wind Speed(km/h)         19190 non-null  float64
 9   Gust(km/h)               19190 non-null  float64
 10  Wind Direction           19190 non-null  str
 11  DewPoint(°C)             19190 non-null  float64
 12  WindChill(°C)            19190 non-null  float64
 13  Hour Rainfall(mm)        19190 non-null  float64
 14  24 Hour Rainfall(mm)     19190 non-null  float64
 15  Week Rainfall(mm)        19190 non-null  float64
 16  Month Rainfall(mm)       19190 non-null  float64
 17  Total Rainfall(mm)       19190 non-null  float64
 18  Light(lux)               19190 non-null  float64
 19  UVI                      19190 non-null  int64
 20  Time_dt                  19190 non-null  datetime64[us]
 21  delta                    19189 non-null  timedelta64[us]
dtypes: datetime64[us](1), float64(14), int64(4), str(2), timedelta64[us](1)
memory usage: 3.9 MB

In [164]:
m[m['Wind Direction'] == '---']

,Time,Interval,Indoor Temperature(°C),Indoor Humidity(%),Outdoor Temperature(°C),Outdoor Humidity(%),Relative Pressure(hpa),Absolute Pressure(hpa),Wind Speed(km/h),Gust(km/h),...,WindChill(°C),Hour Rainfall(mm),24 Hour Rainfall(mm),Week Rainfall(mm),Month Rainfall(mm),Total Rainfall(mm),Light(lux),UVI,Time_dt,delta
6260,2018/08/31 9:06:48 a.m.,30,22.4,68,22.4,62,1011.5,826.2,11.2,15.8,...,20.9,0.0,0.0,6.0,98.4,149.4,45814.0,0,2018-08-31 09:06:48,0 days 00:30:00
8211,2018/10/11 5:21:42 p.m.,30,25.1,47,22.6,52,1010.6,825.3,3.6,7.2,...,22.6,0.0,19.2,51.0,96.3,364.8,19696.1,0,2018-10-11 17:21:42,0 days 00:30:00
12403,2019/02/15 11:53:46 a.m.,30,26.0,58,27.4,49,1012.3,827.0,7.2,9.7,...,27.1,0.0,0.0,32.7,38.1,1629.9,80932.4,0,2019-02-15 11:53:46,0 days 00:30:00

In [174]:
print("0's   Columna")
for col in numeric_cols:
    print(m[m[col] == 0], col)

0's   Columna
Empty DataFrame
Columns: [Time, Interval, Indoor Temperature(°C), Indoor Humidity(%), Outdoor Temperature(°C), Outdoor Humidity(%), Relative Pressure(hpa), Absolute Pressure(hpa), Wind Speed(km/h), Gust(km/h), Wind Direction, DewPoint(°C), WindChill(°C), Hour Rainfall(mm), 24 Hour Rainfall(mm), Week Rainfall(mm), Month Rainfall(mm), Total Rainfall(mm), Light(lux), UVI, Time_dt, delta]
Index: []

[0 rows x 22 columns] Indoor Temperature(°C)
Empty DataFrame
Columns: [Time, Interval, Indoor Temperature(°C), Indoor Humidity(%), Outdoor Temperature(°C), Outdoor Humidity(%), Relative Pressure(hpa), Absolute Pressure(hpa), Wind Speed(km/h), Gust(km/h), Wind Direction, DewPoint(°C), WindChill(°C), Hour Rainfall(mm), 24 Hour Rainfall(mm), Week Rainfall(mm), Month Rainfall(mm), Total Rainfall(mm), Light(lux), UVI, Time_dt, delta]
Index: []

[0 rows x 22 columns] Outdoor Temperature(°C)
Empty DataFrame
Columns: [Time, Interval, Indoor Temperature(°C), Indoor Humidity(%), Outdoor Temperature(°C), Outdoor Humidity(%), Relative Pressure(hpa), Absolute Pressure(hpa), Wind Speed(km/h), Gust(km/h), Wind Direction, DewPoint(°C), WindChill(°C), Hour Rainfall(mm), 24 Hour Rainfall(mm), Week Rainfall(mm), Month Rainfall(mm), Total Rainfall(mm), Light(lux), UVI, Time_dt, delta]
Index: []

[0 rows x 22 columns] Relative Pressure(hpa)
Empty DataFrame
Columns: [Time, Interval, Indoor Temperature(°C), Indoor Humidity(%), Outdoor Temperature(°C), Outdoor Humidity(%), Relative Pressure(hpa), Absolute Pressure(hpa), Wind Speed(km/h), Gust(km/h), Wind Direction, DewPoint(°C), WindChill(°C), Hour Rainfall(mm), 24 Hour Rainfall(mm), Week Rainfall(mm), Month Rainfall(mm), Total Rainfall(mm), Light(lux), UVI, Time_dt, delta]
Index: []

[0 rows x 22 columns] Absolute Pressure(hpa)
                            Time  Interval  Indoor Temperature(°C)  \
1        2018/01/01 2:02:06 a.m.        60                    20.8
2        2018/01/01 3:02:06 a.m.        60                    20.6
3        2018/01/01 4:02:06 a.m.        60                    20.5
19       2018/01/01 8:02:06 p.m.        60                    21.3
20       2018/01/01 9:02:06 p.m.        60                    21.1
...                          ...       ...                     ...
15171   12/05/2019 1:46:58 a. m.        30                    22.1
15204   12/05/2019 6:16:58 p. m.        30                    23.8
15206   12/05/2019 7:16:58 p. m.        30                    23.4
15209   12/05/2019 8:46:58 p. m.        30                    22.8
15213  12/05/2019 10:46:58 p. m.        30                    22.4

       Indoor Humidity(%)  Outdoor Temperature(°C)  Outdoor Humidity(%)  \
1                      74                     16.2                   93
2                      75                     15.9                   95
3                      74                     16.0                   95
19                     74                     16.0                   96
20                     75                     15.7                   98
...                   ...                      ...                  ...
15171                  71                     17.1                   94
15204                  74                     20.6                   86
15206                  74                     19.5                   89
15209                  72                     18.1                   93
15213                  72                     17.3                   92

       Relative Pressure(hpa)  Absolute Pressure(hpa)  Wind Speed(km/h)  \
1                      1012.2                   825.9               0.0
2                      1012.0                   825.7               0.0
3                      1011.7                   825.4               0.0
19                     1012.9                   826.6               0.0
20                     1013.7                   827.4               0.0
...                       ...                     ...               ...
15171                  1014.2                   826.8               0.0
15204                  1012.6                   825.2               0.0
15206                  1012.2                   824.8               0.0
15209                  1013.1                   825.7               0.0
15213                  1014.2                   826.8               0.0

       Gust(km/h)  ... WindChill(°C)  Hour Rainfall(mm)  24 Hour Rainfall(mm)  \
1             0.0  ...          16.2                0.0                   0.0
2             0.0  ...          15.9                0.0                   0.0
3             1.1  ...          16.0                0.0                   0.0
19            1.1  ...          16.0                7.5                  10.2
20            1.1  ...          15.7                3.3                  13.5
...           ...  ...           ...                ...                   ...
15171         1.1  ...          17.1                0.0                   0.3
15204         1.1  ...          20.6                0.0                   1.2
15206         1.1  ...          19.5                0.0                   1.2
15209         0.0  ...          18.1                0.0                   1.2
15213         0.0  ...          17.3                0.0                   1.2

       Week Rainfall(mm)  Month Rainfall(mm)  Total Rainfall(mm)  Light(lux)  \
1                   12.9                 0.0               437.1         0.0
2                   12.9                 0.0               437.1         0.0
3                   12.9                 0.0               437.1         0.0
19                  23.1                10.2               447.3         0.0
20                  26.4                13.5               450.6         0.0
...                  ...                 ...                 ...         ...
15171                0.3                37.8                57.9         0.0
15204                1.2                38.7                58.8      4580.0
15206                1.2                38.7                58.8       641.2
15209                1.2                38.7                58.8         0.0
15213                1.2                38.7                58.8         0.0

       UVI             Time_dt           delta
1        0 2018-01-01 02:02:06 0 days 01:00:00
2        0 2018-01-01 03:02:06 0 days 01:00:00
3        0 2018-01-01 04:02:06 0 days 01:00:00
19       0 2018-01-01 20:02:06 0 days 01:00:00
20       0 2018-01-01 21:02:06 0 days 01:00:00
...    ...                 ...             ...
15171    0 2019-12-05 01:46:58 0 days 00:30:00
15204    0 2019-12-05 18:16:58 0 days 00:30:00
15206    0 2019-12-05 19:16:58 0 days 00:30:00
15209    0 2019-12-05 20:46:58 0 days 00:30:00
15213    0 2019-12-05 22:46:58 0 days 00:30:00

[4302 rows x 22 columns] Wind Speed(km/h)
                            Time  Interval  Indoor Temperature(°C)  \
1        2018/01/01 2:02:06 a.m.        60                    20.8
2        2018/01/01 3:02:06 a.m.        60                    20.6
27       2018/01/02 4:02:06 a.m.        60                    20.4
43       2018/01/02 8:02:06 p.m.        60                    22.0
51       2018/01/03 4:02:06 a.m.        60                    20.8
...                          ...       ...                     ...
15111   10/05/2019 7:46:58 p. m.        30                    23.7
15113   10/05/2019 8:46:58 p. m.        30                    23.0
15160   11/05/2019 8:16:58 p. m.        30                    22.9
15209   12/05/2019 8:46:58 p. m.        30                    22.8
15213  12/05/2019 10:46:58 p. m.        30                    22.4

       Indoor Humidity(%)  Outdoor Temperature(°C)  Outdoor Humidity(%)  \
1                      74                     16.2                   93
2                      75                     15.9                   95
27                     73                     14.8                   99
43                     73                     17.5                   91
51                     74                     16.2                   94
...                   ...                      ...                  ...
15111                  67                     18.6                   86
15113                  67                     17.8                   88
15160                  71                     18.1                   91
15209                  72                     18.1                   93
15213                  72                     17.3                   92

       Relative Pressure(hpa)  Absolute Pressure(hpa)  Wind Speed(km/h)  \
1                      1012.2                   825.9               0.0
2                      1012.0                   825.7               0.0
27                     1011.7                   825.4               0.0
43                     1011.0                   824.7               0.0
51                     1010.7                   824.4               0.0
...                       ...                     ...               ...
15111                  1013.1                   825.7               0.0
15113                  1013.4                   826.0               0.0
15160                  1012.9                   825.5               0.0
15209                  1013.1                   825.7               0.0
15213                  1014.2                   826.8               0.0

       Gust(km/h)  ... WindChill(°C)  Hour Rainfall(mm)  24 Hour Rainfall(mm)  \
1             0.0  ...          16.2                0.0                   0.0
2             0.0  ...          15.9                0.0                   0.0
27            0.0  ...          14.8                0.0                   1.8
43            0.0  ...          17.5                0.0                   2.1
51            0.0  ...          16.2                0.0                   0.0
...           ...  ...           ...                ...                   ...
15111         0.0  ...          18.6                0.0                  10.2
15113         0.0  ...          17.8                0.0                  10.2
15160         0.0  ...          18.1                0.0                   3.3
15209         0.0  ...          18.1                0.0                   1.2
15213         0.0  ...          17.3                0.0                   1.2

       Week Rainfall(mm)  Month Rainfall(mm)  Total Rainfall(mm)  Light(lux)  \
1                   12.9                 0.0               437.1         0.0
2                   12.9                 0.0               437.1         0.0
27                  29.4                16.5               453.6         0.0
43                  29.7                16.8               453.9         0.0
51                  29.7                16.8               453.9         0.0
...                  ...                 ...                 ...         ...
15111               33.6                33.6                53.7         0.0
15113               33.6                33.6                53.7         0.0
15160               36.9                36.9                57.0         0.0
15209                1.2                38.7                58.8         0.0
15213                1.2                38.7                58.8         0.0

       UVI             Time_dt           delta
1        0 2018-01-01 02:02:06 0 days 01:00:00
2        0 2018-01-01 03:02:06 0 days 01:00:00
27       0 2018-01-02 04:02:06 0 days 01:00:00
43       0 2018-01-02 20:02:06 0 days 01:00:00
51       0 2018-01-03 04:02:06 0 days 01:00:00
...    ...                 ...             ...
15111    0 2019-10-05 19:46:58 0 days 00:30:00
15113    0 2019-10-05 20:46:58 0 days 00:30:00
15160    0 2019-11-05 20:16:58 0 days 00:30:00
15209    0 2019-12-05 20:46:58 0 days 00:30:00
15213    0 2019-12-05 22:46:58 0 days 00:30:00

[1356 rows x 22 columns] Gust(km/h)
Empty DataFrame
Columns: [Time, Interval, Indoor Temperature(°C), Indoor Humidity(%), Outdoor Temperature(°C), Outdoor Humidity(%), Relative Pressure(hpa), Absolute Pressure(hpa), Wind Speed(km/h), Gust(km/h), Wind Direction, DewPoint(°C), WindChill(°C), Hour Rainfall(mm), 24 Hour Rainfall(mm), Week Rainfall(mm), Month Rainfall(mm), Total Rainfall(mm), Light(lux), UVI, Time_dt, delta]
Index: []

[0 rows x 22 columns] DewPoint(°C)
Empty DataFrame
Columns: [Time, Interval, Indoor Temperature(°C), Indoor Humidity(%), Outdoor Temperature(°C), Outdoor Humidity(%), Relative Pressure(hpa), Absolute Pressure(hpa), Wind Speed(km/h), Gust(km/h), Wind Direction, DewPoint(°C), WindChill(°C), Hour Rainfall(mm), 24 Hour Rainfall(mm), Week Rainfall(mm), Month Rainfall(mm), Total Rainfall(mm), Light(lux), UVI, Time_dt, delta]
Index: []

[0 rows x 22 columns] WindChill(°C)
                            Time  Interval  Indoor Temperature(°C)  \
0        2018/01/01 1:02:06 a.m.        60                    20.8
1        2018/01/01 2:02:06 a.m.        60                    20.8
2        2018/01/01 3:02:06 a.m.        60                    20.6
3        2018/01/01 4:02:06 a.m.        60                    20.5
4        2018/01/01 5:02:06 a.m.        60                    20.5
...                          ...       ...                     ...
15211   12/05/2019 9:46:58 p. m.        30                    22.6
15212  12/05/2019 10:16:58 p. m.        30                    22.5
15213  12/05/2019 10:46:58 p. m.        30                    22.4
15214  12/05/2019 11:16:58 p. m.        30                    22.3
15215  12/05/2019 11:46:58 p. m.        30                    22.2

       Indoor Humidity(%)  Outdoor Temperature(°C)  Outdoor Humidity(%)  \
0                      74                     16.1                   93
1                      74                     16.2                   93
2                      75                     15.9                   95
3                      74                     16.0                   95
4                      75                     15.6                   95
...                   ...                      ...                  ...
15211                  73                     17.8                   92
15212                  72                     17.5                   92
15213                  72                     17.3                   92
15214                  71                     17.2                   93
15215                  71                     17.3                   93

       Relative Pressure(hpa)  Absolute Pressure(hpa)  Wind Speed(km/h)  \
0                      1013.0                   826.7               1.1
1                      1012.2                   825.9               0.0
2                      1012.0                   825.7               0.0
3                      1011.7                   825.4               0.0
4                      1012.0                   825.7               1.1
...                       ...                     ...               ...
15211                  1013.5                   826.1               1.1
15212                  1014.1                   826.7               3.6
15213                  1014.2                   826.8               0.0
15214                  1014.3                   826.9               1.1
15215                  1014.6                   827.2               2.5

       Gust(km/h)  ... WindChill(°C)  Hour Rainfall(mm)  24 Hour Rainfall(mm)  \
0             3.6  ...          16.1                0.0                   0.0
1             0.0  ...          16.2                0.0                   0.0
2             0.0  ...          15.9                0.0                   0.0
3             1.1  ...          16.0                0.0                   0.0
4             2.5  ...          15.6                0.0                   0.0
...           ...  ...           ...                ...                   ...
15211         2.5  ...          17.8                0.0                   1.2
15212         5.0  ...          17.5                0.0                   1.2
15213         0.0  ...          17.3                0.0                   1.2
15214         2.5  ...          17.2                0.0                   1.2
15215         5.0  ...          17.3                0.0                   1.2

       Week Rainfall(mm)  Month Rainfall(mm)  Total Rainfall(mm)  Light(lux)  \
0                   12.9                 0.0               437.1         0.0
1                   12.9                 0.0               437.1         0.0
2                   12.9                 0.0               437.1         0.0
3                   12.9                 0.0               437.1         0.0
4                   12.9                 0.0               437.1         0.0
...                  ...                 ...                 ...         ...
15211                1.2                38.7                58.8         0.0
15212                1.2                38.7                58.8         0.0
15213                1.2                38.7                58.8         0.0
15214                1.2                38.7                58.8         0.0
15215                1.2                38.7                58.8         0.0

       UVI             Time_dt           delta
0        0 2018-01-01 01:02:06             NaT
1        0 2018-01-01 02:02:06 0 days 01:00:00
2        0 2018-01-01 03:02:06 0 days 01:00:00
3        0 2018-01-01 04:02:06 0 days 01:00:00
4        0 2018-01-01 05:02:06 0 days 01:00:00
...    ...                 ...             ...
15211    0 2019-12-05 21:46:58 0 days 00:30:00
15212    0 2019-12-05 22:16:58 0 days 00:30:00
15213    0 2019-12-05 22:46:58 0 days 00:30:00
15214    0 2019-12-05 23:16:58 0 days 00:30:00
15215    0 2019-12-05 23:46:58 0 days 00:30:00

[17339 rows x 22 columns] Hour Rainfall(mm)
                            Time  Interval  Indoor Temperature(°C)  \
0        2018/01/01 1:02:06 a.m.        60                    20.8
1        2018/01/01 2:02:06 a.m.        60                    20.8
2        2018/01/01 3:02:06 a.m.        60                    20.6
3        2018/01/01 4:02:06 a.m.        60                    20.5
4        2018/01/01 5:02:06 a.m.        60                    20.5
...                          ...       ...                     ...
15122   11/05/2019 1:16:58 a. m.        30                    22.4
15123   11/05/2019 1:46:58 a. m.        30                    22.3
15124   11/05/2019 2:16:58 a. m.        30                    22.3
15125   11/05/2019 2:46:58 a. m.        30                    22.3
15168  12/05/2019 12:16:58 a. m.        30                    22.2

       Indoor Humidity(%)  Outdoor Temperature(°C)  Outdoor Humidity(%)  \
0                      74                     16.1                   93
1                      74                     16.2                   93
2                      75                     15.9                   95
3                      74                     16.0                   95
4                      75                     15.6                   95
...                   ...                      ...                  ...
15122                  67                     16.7                   90
15123                  67                     16.9                   90
15124                  67                     16.9                   89
15125                  67                     16.8                   90
15168                  70                     17.2                   92

       Relative Pressure(hpa)  Absolute Pressure(hpa)  Wind Speed(km/h)  \
0                      1013.0                   826.7               1.1
1                      1012.2                   825.9               0.0
2                      1012.0                   825.7               0.0
3                      1011.7                   825.4               0.0
4                      1012.0                   825.7               1.1
...                       ...                     ...               ...
15122                  1013.9                   826.5               0.0

In [169]:
len(m[m['Indoor Humidity(%)'] == 0])

0

In [175]:
m['Interval'].unique()

array([ 60,  62,  68,   4,  96,  61,  30,  45,  41,  47,  35,  36,  31,
       103,  46,  39,  78,  98,  63,  27,  32,  33,  38,  85,  50,  42,
        55,  40,  92,  19,  53])

In [ ]:
print(m[["Time", "Interval"]].head(20))

                        Time  Interval
0    2018/01/01 1:02:06 a.m.        60
1    2018/01/01 2:02:06 a.m.        60
2    2018/01/01 3:02:06 a.m.        60
3    2018/01/01 4:02:06 a.m.        60
4    2018/01/01 5:02:06 a.m.        60
5    2018/01/01 6:02:06 a.m.        60
6    2018/01/01 7:02:06 a.m.        60
7    2018/01/01 8:02:06 a.m.        60
8    2018/01/01 9:02:06 a.m.        60
9   2018/01/01 10:02:06 a.m.        60
10  2018/01/01 11:02:06 a.m.        60
11  2018/01/01 12:02:06 p.m.        60
12   2018/01/01 1:02:06 p.m.        60
13   2018/01/01 2:02:06 p.m.        60
14   2018/01/01 3:02:06 p.m.        60
15   2018/01/01 4:02:06 p.m.        60
16   2018/01/01 5:02:06 p.m.        60
17   2018/01/01 6:02:06 p.m.        60
18   2018/01/01 7:02:06 p.m.        60
19   2018/01/01 8:02:06 p.m.        60

In [180]:
print(m[["Time", "Interval"]].tail(20))

                            Time  Interval
15196   12/05/2019 2:16:58 p. m.        30
15197   12/05/2019 2:46:58 p. m.        30
15198   12/05/2019 3:16:58 p. m.        30
15199   12/05/2019 3:46:58 p. m.        30
15200   12/05/2019 4:16:58 p. m.        30
15201   12/05/2019 4:46:58 p. m.        30
15202   12/05/2019 5:16:58 p. m.        30
15203   12/05/2019 5:46:58 p. m.        30
15204   12/05/2019 6:16:58 p. m.        30
15205   12/05/2019 6:46:58 p. m.        30
15206   12/05/2019 7:16:58 p. m.        30
15207   12/05/2019 7:46:58 p. m.        30
15208   12/05/2019 8:16:58 p. m.        30
15209   12/05/2019 8:46:58 p. m.        30
15210   12/05/2019 9:16:58 p. m.        30
15211   12/05/2019 9:46:58 p. m.        30
15212  12/05/2019 10:16:58 p. m.        30
15213  12/05/2019 10:46:58 p. m.        30
15214  12/05/2019 11:16:58 p. m.        30
15215  12/05/2019 11:46:58 p. m.        30

In [182]:
print(m.groupby("Interval")["delta"].agg(
    ["count", "min", "max"]
).sort_values("count", ascending=False))

          count             min              max
Interval
30        16975 0 days 00:01:00 34 days 14:42:40
60         2153 0 days 00:04:14 21 days 09:21:04
31           15 0 days 00:31:00  0 days 00:31:00
35            4 0 days 00:35:00  0 days 00:35:00
41            3 0 days 00:41:00  0 days 00:41:00
46            3 0 days 00:46:00  0 days 00:46:00
32            3 0 days 00:32:00  0 days 00:32:00
42            2 0 days 00:42:00  0 days 00:42:00
78            2 0 days 01:18:00  0 days 01:18:00
98            2 0 days 01:38:00  0 days 01:38:00
62            2 0 days 00:45:46  0 days 00:55:46
47            2 0 days 00:47:00  0 days 00:47:00
50            2 0 days 00:50:00  0 days 00:50:00
36            2 0 days 00:36:00  0 days 00:36:00
39            2 0 days 00:39:00  0 days 00:39:00
63            2 0 days 01:03:00  0 days 01:03:00
45            1 0 days 00:45:00  0 days 00:45:00
38            1 0 days 00:38:00  0 days 00:38:00
40            1 0 days 00:40:00  0 days 00:40:00
27            1 0 days 00:27:00  0 days 00:27:00
19            1 0 days 00:19:00  0 days 00:19:00
4             1 0 days 00:04:00  0 days 00:04:00
33            1 0 days 00:33:00  0 days 00:33:00
61            1 0 days 01:01:00  0 days 01:01:00
55            1 0 days 00:55:00  0 days 00:55:00
53            1 0 days 00:53:00  0 days 00:53:00
68            1 0 days 00:53:46  0 days 00:53:46
85            1 0 days 01:25:00  0 days 01:25:00
92            1 0 days 01:32:00  0 days 01:32:00
96            1 0 days 01:36:00  0 days 01:36:00
103           1 0 days 01:43:00  0 days 01:43:00

In [183]:
periodo["Interval"].value_counts()

Interval
30     6812
31        6
46        2
39        2
78        2
98        2
63        2
103       1
35        1
41        1
27        1
32        1
33        1
38        1
36        1
Name: count, dtype: int64